### ISSUE TITLE
Whitelist Problem

### ISSUE THREAD

**Issue by neokill** [zhaojh329/wifidog-ng#10]
Hi, i'm having problem with whitelist domain. Even default qq and baidu doesn't work. Wildcard (*.domain.com) are supported?i tried but give me error while parsing. thanks

**Comment by zhaojh329** [comment]
Please show the ipset info.

ipset list

**Comment by neokill** [comment]
ipset list:
192.168.1.113
216.58.205.106
172.217.23.106
216.58.198.10
185.60.216.35
216.58.205.42
216.58.205.74
216.58.205.170
172.217.23.74
216.58.205.138
216.58.205.202
216.58.198.42
157.240.20.35


In the config :
config whitelist_domain
	option domain 'facebook.net'

config whitelist_domain
	option domain 'fbcdn.net'

config whitelist_domain
	option domain 'maps.googleapis.com'

config whitelist_domain
	option domain 'akamaihd.net'

config whitelist_domain
	option domain 'facebook.com'

**Comment by zhaojh329** [comment]
It looks like no problem.

**Comment by neokill** [comment]
I still have issue. The wildcard is accepted?

**Comment by zhaojh329** [comment]
You are talking about the pan-domain name resolution.I need to confirm whether it supports

**Comment by zhaojh329** [comment]
Does not support, I need to fix it.

**Comment by zhaojh329** [comment]
Re implemented in Lua and fixed your problem.
