### ISSUE TITLE
modprobe fails to load wifidog-ng module

### ISSUE THREAD

**Issue by jdegraef** [zhaojh329/wifidog-ng#15]
installed wifidog-ng on 18.06, 
/etc/init.d/wifidog-ng start fails to load kernel module more details below

i think the load works fine the very first time, but then fails afterwards
also note that i'm not using br-lan but Guest as the interface. (FWIW I also tried wlan1-1)
dmesg only gave info on br-lan ... but not sure if that is from the very first load or not.

`
root@router:/etc/config# cat wifidog-ng
config gateway
    option enabled 0
    option ifname 'Guest'
    option port 2060
    option ssl_port 8443
    option checkinterval 30
    option client_timeout 5
    option temppass_time 30

config authserver
    option host '10.0.0.1'
    option port 80
    option ssl 0
    option path '/cgi-bin/luci/auth/'
    option login_path 'login'
    option portal_path 'portal'
    option msg_path 'gw_message.php'
    option ping_path 'ping'
    option auth_path 'auth'

config popularserver
    list server www.baidu.com
    list server www.qq.com

config whitelist
`

`
root@router:/etc/config# opkg list-installed | grep wifidog
kmod-wifidog-ng - 4.9.111+1.5.6-1
wifidog-ng-mbedtls - 1.5.6-1
root@router:/etc/config# opkg list-installed | grep mbedtls
libmbedtls - 2.12.0-1
libuhttpd-mbedtls - 2.0.3-1
libustream-mbedtls - 2018-05-22-5322f9db-1
wifidog-ng-mbedtls - 1.5.6-1
root@router:/etc/config# cat /etc/os-release
NAME="OpenWrt"
VERSION="18.06.0"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 18.06.0"
VERSION_ID="18.06.0"
HOME_URL="http://openwrt.org/"
BUG_URL="http://bugs.openwrt.org/"
SUPPORT_URL="http://forum.lede-project.org/"
BUILD_ID="r7188-b0b5c64c22"
LEDE_BOARD="ar71xx/nand"
LEDE_ARCH="mips_24kc"
LEDE_TAINTS=""
LEDE_DEVICE_MANUFACTURER="OpenWrt"
LEDE_DEVICE_MANUFACTURER_URL="http://openwrt.org/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="OpenWrt 18.06.0 r7188-b0b5c64c22"
root@router:/etc/config# uname -a
Linux router 4.9.111 #0 Mon Jul 30 16:25:17 2018 mips GNU/Linux
root@router:/etc/config# modprobe /lib/modules/4.9.111/wifidog-ng.ko
1 module could not be probed
- wifidog-ng
root@router:/etc/config#
`

**Comment by KazukiShimada** [comment]
Hi.
I also met this issue sometimes.
It seems kmodloader fails to load kmod-wifidog-ng.

**Comment by zhaojh329** [comment]
Please try 'modprobe wifidog-ng' or 'insmod /lib/modules/4.9.111/wifidog-ng.ko'
