### ISSUE TITLE
Configure timeout of MAC Address

### ISSUE THREAD

**Issue by sah-anshu** [zhaojh329/wifidog-ng#26]
I have setup the Lease time of 2 hrs but still timeout of MAC is 4294967. Can you please advise how to we set this value.  

root@Infi:~# ipset list wifidog-ng-mac
Name: wifidog-ng-mac
Type: hash:mac
Revision: 0
Header: hashsize 1024 maxelem 65536 timeout 4294967
Size in memory: 192
References: 0
Members:
**38:C9:86:16:8A:37 timeout 4294904**

![screenshot 2018-10-27 at 3 39 30 pm](https://user-images.githubusercontent.com/9985291/47602586-a8b2a280-d9fe-11e8-9916-da3cb218f8d7.png)

Thanks in advance.

**Comment by zhaojh329** [comment]
Lease time and authentication timeout have no relationship.

**Comment by sah-anshu** [comment]
Is there any way, i can control these values.  pl advice.

**Comment by zhaojh329** [comment]
No.
