### ISSUE TITLE
setment fault on netgear R7800, latest version (wifidog-ng-nossl	1.5.6-1)

### ISSUE THREAD

**Issue by wjx0912** [zhaojh329/wifidog-ng#27]
root@OpenWrt:~# 
root@OpenWrt:~# strace wifidog-ng 
execve("/usr/bin/wifidog-ng", ["wifidog-ng"], 0xbed14df0 /* 12 vars */) = 0
set_tls(0xb6f75544, 0xbe81dc28, 0x4908aab4, 0, 0xb6f754a0) = 0
set_tid_address(0xb6f754bc)             = 5392
open("/etc/ld-musl-armhf.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libuhttpd.so.2.0.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libuhttpd.so.2.0.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libuhttpd.so.2.0.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=28675, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\260\33\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 118784, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6ee2000
mmap2(0xb6ef8000, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x6000) = 0xb6ef8000
mmap2(0xb6efa000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6efa000
close(3)                                = 0
open("/lib/libubox.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=32821, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\340\37\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 102400, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6ec9000
mmap2(0xb6ee0000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x7000) = 0xb6ee0000
close(3)                                = 0
open("/lib/libuci.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0755, st_size=32811, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\210\24\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 102400, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6eb0000
mmap2(0xb6ec7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x7000) = 0xb6ec7000
close(3)                                = 0
open("/lib/libuclient.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libuclient.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libuclient.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=16393, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0000\22\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 86016, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6e9b000
mmap2(0xb6eae000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x3000) = 0xb6eae000
close(3)                                = 0
open("/lib/libblobmsg_json.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=8195, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0x\n\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 77824, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6e88000
mmap2(0xb6e99000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x1000) = 0xb6e99000
close(3)                                = 0
open("/lib/libubus.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=20582, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\374\21\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 90112, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6e72000
mmap2(0xb6e86000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x4000) = 0xb6e86000
close(3)                                = 0
open("/lib/libcares.so.2", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libcares.so.2", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libcares.so.2", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0755, st_size=57458, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\240\31\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 126976, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6e53000
mmap2(0xb6e70000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xd000) = 0xb6e70000
close(3)                                = 0
open("/lib/libipset.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libipset.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libipset.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0755, st_size=158723, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0000\221\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 225280, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6e1c000
mmap2(0xb6e49000, 40960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x1d000) = 0xb6e49000
close(3)                                = 0
open("/lib/libpcap.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libpcap.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libpcap.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=188649, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\250M\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 258048, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6ddd000
mmap2(0xb6e1a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2d000) = 0xb6e1a000
close(3)                                = 0
open("/lib/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=45347, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\20<\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 114688, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6dc1000
mmap2(0xb6ddb000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xa000) = 0xb6ddb000
close(3)                                = 0
open("/lib/liblua.so.5.1.5", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/liblua.so.5.1.5", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/liblua.so.5.1.5", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=122883, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0`9\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 192512, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6d92000
mmap2(0xb6dbf000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x1d000) = 0xb6dbf000
close(3)                                = 0
open("/lib/libjson-c.so.2", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libjson-c.so.2", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libjson-c.so.2", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0755, st_size=28692, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\0\36\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 98304, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6d7a000
mmap2(0xb6d90000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x6000) = 0xb6d90000
close(3)                                = 0
open("/lib/libmnl.so.0", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libmnl.so.0", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libmnl.so.0", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0755, st_size=12291, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\370\23\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 81920, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6d66000
mmap2(0xb6d78000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0xb6d78000
close(3)                                = 0
mprotect(0xb6ef8000, 4096, PROT_READ)   = 0
mprotect(0xb6ee0000, 4096, PROT_READ)   = 0
mprotect(0xb6ec7000, 4096, PROT_READ)   = 0
mprotect(0xb6eae000, 4096, PROT_READ)   = 0
mprotect(0xb6e99000, 4096, PROT_READ)   = 0
mprotect(0xb6e86000, 4096, PROT_READ)   = 0
mprotect(0xb6e70000, 4096, PROT_READ)   = 0
mprotect(0xb6e49000, 28672, PROT_READ)  = 0
mprotect(0xb6e1a000, 4096, PROT_READ)   = 0
mprotect(0xb6ddb000, 4096, PROT_READ)   = 0
mprotect(0xb6dbf000, 4096, PROT_READ)   = 0
mprotect(0xb6d90000, 4096, PROT_READ)   = 0
mprotect(0xb6d78000, 4096, PROT_READ)   = 0
mprotect(0x29000, 4096, PROT_READ)      = 0
brk(NULL)                               = 0xa24000
brk(0xa28000)                           = 0xa28000
socket(AF_NETLINK, SOCK_RAW, NETLINK_NETFILTER) = 3
bind(3, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
getsockname(3, {sa_family=AF_NETLINK, nl_pid=5392, nl_groups=00000000}, [12]) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1542197340, tv_nsec=47813856}) = 0
sendto(3, {{len=28, type=0x601 /* NLMSG_??? */, flags=NLM_F_REQUEST, seq=1542197341, pid=0}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x00\x00\x00"}, 28, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 28
recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=28, type=0x601 /* NLMSG_??? */, flags=0, seq=1542197341, pid=5392}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x00\x00\x00"}, iov_len=256}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 28
sendto(3, {{len=52, type=0x60d /* NLMSG_??? */, flags=NLM_F_REQUEST, seq=1542197342, pid=0}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x00\x00\x00\x0d\x00\x03\x00\x68\x61\x73\x68\x3a\x6d\x61\x63\x00\x00\x00\x00\x05\x00\x05\x00"...}, 52, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 52
recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=68, type=0x60d /* NLMSG_??? */, flags=0, seq=1542197342, pid=5392}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x00\x00\x00\x0d\x00\x03\x00\x68\x61\x73\x68\x3a\x6d\x61\x63\x00\x00\x00\x00\x05\x00\x05\x00"...}, iov_len=256}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 68
sendto(3, {{len=92, type=0x602 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK|0x400, seq=1542197343, pid=0}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x00\x00\x00\x13\x00\x02\x00\x77\x69\x66\x69\x64\x6f\x67\x2d\x6e\x67\x2d\x6d\x61\x63\x00\x00"...}, 92, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 92
recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=36, type=NLMSG_ERROR, flags=NLM_F_CAPPED, seq=1542197343, pid=5392}, {error=0, msg={len=92, type=0x602 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK|0x400, seq=1542197343, pid=0}}}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 36
sendto(3, {{len=48, type=0x60d /* NLMSG_??? */, flags=NLM_F_REQUEST, seq=1542197344, pid=0}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x00\x00\x00\x0c\x00\x03\x00\x68\x61\x73\x68\x3a\x69\x70\x00\x05\x00\x05\x00\x02\x00\x00\x00"}, 48, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 48
recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=64, type=0x60d /* NLMSG_??? */, flags=0, seq=1542197344, pid=5392}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x00\x00\x00\x0c\x00\x03\x00\x68\x61\x73\x68\x3a\x69\x70\x00\x05\x00\x05\x00\x02\x00\x00\x00"...}, iov_len=256}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 64
sendto(3, {{len=80, type=0x602 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK|0x400, seq=1542197345, pid=0}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x06\x05\x04\x12\x00\x02\x00\x77\x69\x66\x69\x64\x6f\x67\x2d\x6e\x67\x2d\x69\x70\x00\x00\x00"...}, 80, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 80
recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=36, type=NLMSG_ERROR, flags=NLM_F_CAPPED, seq=1542197345, pid=5392}, {error=0, msg={len=80, type=0x602 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK|0x400, seq=1542197345, pid=0}}}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 36
sendto(3, {{len=48, type=0x604 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1542197346, pid=0}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x06\x05\x04\x13\x00\x02\x00\x77\x69\x66\x69\x64\x6f\x67\x2d\x6e\x67\x2d\x6d\x61\x63\x00\x00"}, 48, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 48
recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=36, type=NLMSG_ERROR, flags=NLM_F_CAPPED, seq=1542197346, pid=5392}, {error=0, msg={len=48, type=0x604 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1542197346, pid=0}}}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 36
sendto(3, {{len=48, type=0x604 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1542197347, pid=0}, "\x02\x00\x00\x00\x05\x00\x01\x00\x06\x06\x05\x00\x12\x00\x02\x00\x77\x69\x66\x69\x64\x6f\x67\x2d\x6e\x67\x2d\x69\x70\x00\x00\x00"}, 48, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 48
recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=36, type=NLMSG_ERROR, flags=NLM_F_CAPPED, seq=1542197347, pid=5392}, {error=0, msg={len=48, type=0x604 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1542197347, pid=0}}}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 36
stat64("/etc/config/wifidog-ng", {st_mode=S_IFREG|0600, st_size=563, ...}) = 0
open("/etc/config/wifidog-ng", O_RDONLY|O_LARGEFILE) = 4
flock(4, LOCK_SH)                       = 0
_llseek(4, 0, [0], SEEK_SET)            = 0
readv(4, [{iov_base="", iov_len=0}, {iov_base="config gateway\n    option enable"..., iov_len=1024}], 2) = 563
readv(4, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
stat64("/tmp/.uci/wifidog-ng", 0xbe81d6e8) = -1 ENOENT (No such file or directory)
stat64("/tmp/.uci/wifidog-ng", 0xbe81d898) = -1 ENOENT (No such file or directory)
flock(4, LOCK_UN)                       = 0
close(4)                                = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
ioctl(4, SIOCGIFHWADDR, {ifr_name="br-lan", ifr_hwaddr=8c:3b:ad:b6:d6:5b}) = 0
close(4)                                = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
ioctl(4, SIOCGIFADDR, {ifr_name="br-lan", ifr_addr={sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("192.168.1.1")}}) = 0
close(4)                                = 0
open("/proc/wifidog-ng/config", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = 4
ioctl(4, TIOCGWINSZ, 0xbe81dc78)        = -1 ENOTTY (Not a tty)
writev(4, [{iov_base="port=2060\nssl_port=8443\nclient_t"..., iov_len=60}, {iov_base=NULL, iov_len=0}], 2) = 60
close(4)                                = 0
epoll_create1(0)                        = 4
fcntl64(4, F_GETFD)                     = 0
fcntl64(4, F_SETFD, FD_CLOEXEC)         = 0
pipe([5, 6])                            = 0
fcntl64(5, F_GETFD)                     = 0
fcntl64(5, F_SETFD, FD_CLOEXEC)         = 0
fcntl64(5, F_GETFL)                     = 0 (flags O_RDONLY)
fcntl64(5, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
fcntl64(6, F_GETFD)                     = 0
fcntl64(6, F_SETFD, FD_CLOEXEC)         = 0
fcntl64(6, F_GETFL)                     = 0x1 (flags O_WRONLY)
fcntl64(6, F_SETFL, O_WRONLY|O_NONBLOCK|O_LARGEFILE) = 0
fcntl64(5, F_GETFL)                     = 0x800 (flags O_RDONLY|O_NONBLOCK)
fcntl64(5, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLRDHUP, {u32=3069055008, u64=3069055008}}) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0xb6ecc964, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0xb6ecc964, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, NULL, 8) = 0
rt_sigaction(SIGCHLD, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=0xb6ecc94c, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, NULL, 8) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, NULL, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=0xb6ecc964, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=0xb6ecc964, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, 8) = 0
rt_sigaction(SIGCHLD, NULL, {sa_handler=0xb6ecc94c, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, 8) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6f40560}, 8) = 0
brk(0xa39000)                           = 0xa39000
socket(AF_UNIX, SOCK_STREAM, 0)         = 7
fcntl64(7, F_GETFD)                     = 0
fcntl64(7, F_SETFD, FD_CLOEXEC)         = 0
connect(7, {sa_family=AF_UNIX, sun_path="/var/run/ubus.sock"}, 110) = 0
read(7, "\0\0\0\0\340\271\17\217\0\0\0\4", 12) = 12
read(7, "", 0)                          = 0
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(7, F_SETFL, O_RDWR|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLRDHUP, {u32=10649436, u64=10649436}}) = 0
sendmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0\6\0\1\0\0\0\0", iov_len=8}, {iov_base="\0\0\1\0\2\0\0\17wifidog-ng\0\0\6\0\0\354\202\0\0000\0\4te"..., iov_len=256}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, 0) = 264
poll([{fd=7, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0\2\0\1\0\0\0\0\0\0\0\24", iov_len=12}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 12
poll([{fd=7, events=POLLIN}], 1, -1)    = 1 ([{fd=7, revents=POLLIN}])
recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\3\0\0\10\356O\355\241\5\0\0\10*\265m]", iov_len=16}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 16
recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0\1\0\1\0\0\0\0\0\0\0\f", iov_len=12}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 12
poll([{fd=7, events=POLLIN}], 1, -1)    = 1 ([{fd=7, revents=POLLIN}])
recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\0\10\0\0\0\0", iov_len=8}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 8
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 8
fcntl64(8, F_GETFD)                     = 0
fcntl64(8, F_SETFD, FD_CLOEXEC)         = 0
setsockopt(8, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(8, {sa_family=AF_INET, sin_port=htons(2060), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(8, 128)                          = 0
fcntl64(8, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(8, F_SETFL, O_RDWR|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLRDHUP, {u32=3069654948, u64=3069654948}}) = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 9
fcntl64(9, F_GETFD)                     = 0
fcntl64(9, F_SETFD, FD_CLOEXEC)         = 0
setsockopt(9, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(9, {sa_family=AF_INET, sin_port=htons(8443), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(9, 128)                          = 0
fcntl64(9, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(9, F_SETFL, O_RDWR|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 9, {EPOLLIN|EPOLLRDHUP, {u32=3069655316, u64=3069655316}}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
root@OpenWrt:~#

**Comment by zhaojh329** [comment]
Please use the latest version writen in Lua.

**Comment by wjx0912** [comment]
@zhaojh329 
ok, thanks
