### ISSUE TITLE
feeds update wifidog_ng failed

### ISSUE THREAD

**Issue by wjx0912** [zhaojh329/wifidog-ng#28]
**the two step work normal:** 

echo 'src-git wifidog_ng https://github.com/zhaojh329/wifidog-ng.git' >> feeds.conf.default

./scripts/feeds uninstall -a

**but faile at "./scripts/feeds update wifidog_ng"**

`wyt@debian-wyt:~/github/openwrt/openwrt$ ./scripts/feeds update wifidog_ng

Updating feed 'wifidog_ng' from 'https://github.com/zhaojh329/wifidog-ng.git' ...

Already up-to-date.

Create index file './feeds/wifidog_ng.index' 

/home/wyt/github/openwrt/openwrt/feeds/wifidog_ng.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.

wyt@debian-wyt:~/github/openwrt/openwrt$

`

**if not add wifidog-ng, the image compile success. can give some help? thanks.**

**Comment by zhaojh329** [comment]
rm -rf ./feeds/ wifidog_ng*

then redo.

**Comment by wjx0912** [comment]
hi, @zhaojh329 
i just do the command, but still output same error. help~

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/wifidog-ng/blob/master/BUILD.md#other

**Comment by wjx0912** [comment]
@zhaojh329 
hi, thanks for your reply, i have success compile the package(kmod-wifidog-ng.ipk and wifidog-ng.ipk).

but still have a problem:
the default package dasmasq conflict with dasmasq-full(depends by wifidog-ng), i disselect the dasmasq in menuconfig and all compile success. which package should i choose?

thanks.
