### ISSUE TITLE
Walled Garden or URLs allowed before authenticating

### ISSUE THREAD

**Issue by SergioDG-YCC** [zhaojh329/wifidog-ng#36]
Is it possible to create a walled Garden, to allow DNS's, URL's before authentication? In place of IP's. Since large sites like FB or GL use thousands of different ip. Example: Display an ADS during authentication (not after). A login button for FB and WiFiDog simultaneously. Etc. At this point, I seek to work with URLs, not with IP

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/wifidog-ng#section-validated_domain
