### ISSUE TITLE
Gateway ID

### ISSUE THREAD

**Issue by KazukiShimada** [zhaojh329/wifidog-ng#4]
Hi.

Now I try to work wifidog-ng with ar71xx device.
I want to know how I set gateway ID?

Thanks in advance.

**Comment by zhaojh329** [comment]
The setting is not yet supported. Currently, the MAC address of the interface is used as the gateway ID.
This should be supported, or you can submit the code to support it.

**Comment by KazukiShimada** [comment]
I see.
I set mac address as gateway id on my authpuppy server as for now.
Thanks.

**Comment by zhaojh329** [comment]
@KazukiShimada 
In fact, it is supported, but it is not explained. I've updated README.

**Comment by KazukiShimada** [comment]
Ah, OK. I'll try it.

It looks like wifidog-ng was forked from apfree-wifidog.
https://github.com/liudf0716/apfree_wifidog

**Comment by zhaojh329** [comment]
Why? You can compare the code and look at the similarity.

**Comment by KazukiShimada** [comment]
Oh, sorry, I don't read the code.
I thought it because the behavior is similar to apfree-wifidog , like mac address as gateway id.

Anyway thank you to revive wifidog gateway.
