### ISSUE TITLE
Incoming, outgoing traffic

### ISSUE THREAD

**Issue by neokill** [zhaojh329/wifidog-ng#5]
Hi, thanks for your work!
I'm having problem with counter data: Incoming(outgoing too) value is much bigger than i expected and sometimes it's negative. I tried to see if it was a router problem installing luci-app-nlbwmon and the data were correct. I'm using a Tp-link archer c-50 v3. 
Thanks in advance.

**Comment by zhaojh329** [comment]
Sorry, I was too busy recently.
