### ISSUE TITLE
1 module could not be probed - wifidog-ng

### ISSUE THREAD

**Issue by KazukiShimada** [zhaojh329/wifidog-ng#7]
environment: pcengine alix2, x86 geode, openwrt trunk  ac70ac3532fefa78c944d8a26c8df0ca5d88d04e

Hi.
After stopping wifidog-ng intentionally, It fails to start because of this error,
-------------------------------------------------------------------------------------------------
root@OpenWrt:/etc/config#
 /etc/init.d/wifidog-ng start
1 module could not be probed
- wifidog-ng
root@OpenWrt:/etc/config#
-------------------------------------------------------------------------------------------------

After that happens, wifidog-ng never starts.
Here is output of logread.
-------------------------------------------------------------------------------------------------
Wed May 16 13:30:11 2018 kern.info kernel: [  200.207919] kmod of wifidog-ng is stop
Wed May 16 13:31:18 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:31:23 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:31:27 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:31:32 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:31:37 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:31:42 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:31:42 2018 daemon.info procd: Instance wifidog-ng::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Wed May 16 13:31:42 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:31:57 2018 daemon.err wifidog-ng: Kernel module is not loaded
Wed May 16 13:33:13 2018 daemon.err wifidog-ng: Kernel module is not loaded
root@OpenWrt:/etc/config#
-------------------------------------------------------------------------------------------------
Any idea to debug?
Thanks.

**Comment by zhaojh329** [comment]
Please describe in detail how you stopped it

**Comment by KazukiShimada** [comment]
Hi.
After my previous report, I rebooted the device then problem were gone.
I met this issue several times until now. but It's hard to be reproducible. It happened suddenly.

I found out kmodloader printed out "1 module could not be probed".
I'll try to tranking down kmodloader.
