### ISSUE TITLE
What auth servers are compatible with wifidog-ng?

### ISSUE THREAD

**Issue by KazukiShimada** [zhaojh329/wifidog-ng#8]
Hi.

I tried wifidog-ng with wifidog auth server(classic) and authpuppy.
wifidog auth server(classic) - failed to login.
authpuppy - success.

What auth servers are compatible with wifidog-ng?
What auth server do you use?

Thanks.

**Comment by zhaojh329** [comment]
Please see README.md

**Comment by KazukiShimada** [comment]
Test server?....oh....

Anyway thanks!
